name = "SymbolicCRN"
uuid = "16277dbf-7e4a-4f3f-9a2d-e0f06cb41891"
authors = ["Laura Brustenga i Moncusí <brust@math.ku.dk> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
